arch:
  - amd64

language: node_js

node_js:
    - "stable"

services:
    - "mysql"

install:
    - npm install

before_script:
  - mysql -u root < schema.sql;
  - mysql -u root < db_test.sql;
  - npm run seeder
  - npm run server